language: node_js
# https://github.com/zalando-incubator/hexo-theme-doc/issues/149
node_js: 12

# Travis-CI Caching
cache:
  directories:
    - node_modules
    - public/build
    - public/css
    - public/js
    - public/fancybox
    - public/dist
    - public/lib


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "ChenX1993"
  - git config user.email "xc454981894@gmail.com"
  - git add .
  - git commit -m "Site update"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/ChenX1993/blog.git
