sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: ChenX1993/ChenX1993.github.io
    target_branch: master
    email: xc454981894@gmial.com
    name: ChenX1993